version: '3.1'
services:
    mysql:
        restart: always
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - databasevolume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306

    openemr:
        restart: always
        build:
            context: dockerfiles/dev
            args:
                - NGINX_UID=${NGINX_UID}
        ports:
            - ${OPENEMR_PORT}:80
        volumes:
            - ${OPENEMR_SITE_VOLUME}:/var/www/html
            - ./dockerfiles/dev/openemr.conf:/etc/nginx/sites-enabled/openemr.local:ro
            - ./dockerfiles/dev/php.ini:/etc/php/8.1/fpm/php.ini:ro
            - ./dockerfiles/dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
        depends_on:
            - mysql
volumes:
    databasevolume: {}
